#!/usr/bin/env bash
# A simple tmux SSH session manager.

# 1. Determine the host
if [[ $# -eq 1 ]]; then
  selected_host="$1"
else
  # Let user select from ssh config hosts via fzf
  selected_host=$(grep '^Host ' ~/.ssh/config | awk '{print $2}' | rg -v '*' | sk)
fi

# Exit if no host was selected
if [[ -z $selected_host ]]; then
  exit 0
fi

# 2. Create a sanitized session name
session_name="ssh-$(echo "$selected_host" | tr . _)"

# 3. Create session if it doesn't exist
# The `2>/dev/null` silences the "session not found" error.
if ! tmux has-session -t="$session_name" 2>/dev/null; then
  tmux new-session -d -s "$session_name" "ssh $selected_host"
fi

# 4. Attach to the session
if [[ -z "$TMUX" ]]; then
  # We're outside tmux, so attach
  tmux attach-session -t "$session_name"
else
  # We're inside tmux, so switch
  tmux switch-client -t "$session_name"
fi
